Add Context in Host
antoineco/aco-tomcat pull request #86
Opened 2017-10-06 16:20 UTC by HerveMARTIN

See issue #85

2017-10-17 11:17 UTC, awuetz commented
Hello @HerveMARTIN ,

do you know when this feature will be available?

2017-10-17 11:19 UTC, antoineco commented
My fault, I haven't reviewed yet!

2017-10-17 11:26 UTC, awuetz commented
Ok, you would save me a lot of headache, if this would be available.

2017-10-20 07:23 UTC, awuetz commented
Hi @antoineco,

do you know when a new release will be available?
Kind regards.

2017-10-20 07:32 UTC, antoineco commented
@awuetz reviewing right now :)

2017-10-20 08:07 UTC, antoineco requested changes
Please consider my comments, the rest is perfect 👍

2017-10-20 08:07 UTC, antoineco commented on manifests/instance.pp
> +  $host_context        = undef,
You added the parameter here but not the corresponding `concat::fragment` later in the same file.

2017-10-20 08:07 UTC, antoineco commented on manifests/init.pp
> +  $host_context        = undef,
Minor thing: could you please align the equal sign on the other class params?

2017-10-20 08:07 UTC, antoineco commented on manifests/instance.pp
> +  $host_context        = undef,
... and same comment regarding the equal sign alignment.

2017-10-20 08:23 UTC, HerveMARTIN commented
Done :)

2017-10-20 08:25 UTC, antoineco approved these changes

2017-10-20 08:25 UTC, antoineco commented
Thanks Hervé !

2017-10-20 08:25 UTC, merged

2017-10-20 12:06 UTC, awuetz commented
Hi @antoineco,
will you release a new version?

2017-10-20 13:44 UTC, HerveMARTIN commented
At least @awuetz you could use a git ref to this master branch in your Puppetfile.
mod 'aco-tomcat',
    :git => 'https://github.com/antoineco/aco-tomcat'

2017-10-20 17:49 UTC, antoineco commented
Released in [v1.8.3](https://forge.puppet.com/aco/tomcat/1.8.3/readme)